### ISSUE TITLE
add ability to inject arbitrary labels and tolerances to pod template

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/rhg_compute_tools#57]
Allow specifying pod labels & tolerances. Right now must be done with pod template, e.g.:

```yaml
metadata:
  labels:
    key1: val1
    key2: val2
spec:
  tolerations:
  - effect: "NoSchedule"
    key: "k8s.dask.org_dedicated"
    operator: "Equal"
    value: "worker-highcpu"
  - effect: "NoSchedule"
    key: "k8s.dask.org/dedicated"
    operator: "Equal"
    value: "worker-highcpu"
```
